blank_issues_enabled: false
contact_links:
  - name: docs.microsoft.com site feedback
    url: https://github.com/MicrosoftDocs/feedback/issues/new/choose
    about: Log general docs.microsoft.com site issues here
  - name: SkiaSharp product feedback
    url: https://github.com/mono/SkiaSharp/issues
    about: Log SkiaSharp product issues here
