variables:
  SKIASHARP_MAJOR_VERSION: 3
  SKIASHARP_VERSION: 3.116.1
  FEATURE_NAME_PREFIX: 'feature/'
  VERBOSITY: normal
  GIT_SHA: $(Build.SourceVersion)
  GIT_BRANCH_NAME: $(Build.SourceBranch)
  GIT_URL: $(Build.Repository.Uri)
  FEATURE_NAME: ''
  PREVIEW_LABEL: 'stable'
  BUILD_NUMBER: $[counter(format('_{0}_{1}_{2}__', variables['SKIASHARP_VERSION'], variables['Build.SourceBranch'], variables['PREVIEW_LABEL']), 1)]
  BUILD_COUNTER: $[counter('global_counter', 1)]
  TIZEN_LINUX_PACKAGES: libxcb-icccm4 libxcb-render-util0 gettext libxcb-image0 libsdl1.2debian libv4l-0 libxcb-randr0 bridge-utils libxcb-shape0 libpython2.7 openvpn libkf5itemmodels5 libkf5kiowidgets5 libkchart2
  MANAGED_LINUX_PACKAGES: ttf-ancient-fonts ninja-build
  XCODE_VERSION: '15.4'
  XCODE_VERSION_NATIVE: '15.4'
  VISUAL_STUDIO_VERSION: ''
  DOTNET_VERSION: '8.0.304'
  DOTNET_VERSION_PREVIEW: ''
  DOTNET_WORKLOAD_SOURCE: 'https://github.com/dotnet/maui/releases/download/8.0.82/8.0.82.json'
  DOTNET_WORKLOAD_TIZEN: '8.0.149'
  CONFIGURATION: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_DIFF_PRERELEASE: false
  ENABLE_CODE_COVERAGE: true
  EMSCRIPTEN_VERSION: 3.1.34
  Codeql.Enabled: true
  IOS_TEST_DEVICE_VERSION: 17.2
  ANDROID_TEST_DEVICE_VERSION: 34
  ANDROID_PLATFORM_VERSIONS: 21,34
