variables:
  SKIASHARP_VERSION: 3.0.0
  FEATURE_NAME_PREFIX: 'feature/'
  VERBOSITY: normal
  GIT_SHA: $(Build.SourceVersion)
  GIT_BRANCH_NAME: $(Build.SourceBranch)
  GIT_URL: $(Build.Repository.Uri)
  FEATURE_NAME: ''
  PREVIEW_LABEL: 'alpha.1'
  BUILD_NUMBER: $[counter(format('_{0}_{1}_{2}__', variables['SKIASHARP_VERSION'], variables['Build.SourceBranch'], variables['PREVIEW_LABEL']), 1)]
  BUILD_COUNTER: $[counter('global_counter', 1)]
  TIZEN_LINUX_PACKAGES: libxcb-icccm4 libxcb-render-util0 gettext libxcb-image0 libsdl1.2debian libv4l-0 libxcb-randr0 bridge-utils libxcb-shape0 libpython2.7 openvpn
  MANAGED_LINUX_PACKAGES: ttf-ancient-fonts ninja-build
  XCODE_VERSION: 14.2
  VISUAL_STUDIO_VERSION: ''
  DOTNET_VERSION_PREVIEW: '7.0.302'
  DOTNET_WORKLOAD_SOURCE: 'https://maui.blob.core.windows.net/metadata/rollbacks/7.0.81.json'
  DOTNET_WORKLOAD_TIZEN: '7.0.120'
  CONFIGURATION: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_DIFF_PRERELEASE: false
  ENABLE_CODE_COVERAGE: true
  EMSCRIPTEN_VERSION: 3.1.12
  Codeql.Enabled: true
