trigger:
  branches:
    include:
      - main
      - develop
      - release/*
  paths:
    exclude:
      - .devcontainer/**
      - .github/**
      - .vscode/**
      - changelogs/**
      - README.md

pr: none

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build for main
    branches:
      include:
        - main
    always: true

# parameters:
#   - name: buildExternals
#     displayName: 'The Build ID containing the specific native artifacts to use:'
#     type: string
#     default: 'latest'
#   - name: buildAgentHost
#     displayName: 'The generic host build agent configuration:'
#     type: object
#     default:
#       pool:
#         name: Maui-1ESPT
#         image: 1ESPT-Windows2022
#         os: windows
#   - name: buildAgentWindowsNative
#     displayName: 'The Windows build agent configuration for building the native assets:'
#     type: object
#     default:
#       pool:
#         name: Maui-1ESPT
#         image: 1ESPT-Windows2022
#         os: windows
#   - name: buildAgentMacNative
#     displayName: 'The macOS build agent configuration for building the native assets:'
#     type: object
#     default:
#       pool:
#         name: Azure Pipelines
#         vmImage: macos-14
#         os: macos
#   - name: buildAgentLinuxNative
#     displayName: 'The Linux build agent configuration for building the native assets:'
#     type: object
#     default:
#       pool:
#         name: Maui-1ESPT
#         image: 1ESPT-Ubuntu22.04
#         os: linux
#   - name: runCompliance
#     displayName: 'Run post-build compliance tasks (such as API Scan and PoliCheck)'
#     type: boolean
#     default: false

# variables:
#   - template: /scripts/azure-templates-variables.yml@self

resources:
  repositories:
    - repository: yaml-templates
      type: git
      name: DevDiv/Xamarin.yaml-templates
      ref: refs/heads/main
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: prepare
        displayName: Prepare Build
        jobs:
          - job: prepare
            displayName: Prepare Build
            pool:
              name: AzurePipelines-EO
              image: 1ESPT-Windows2022
              os: windows
            steps:
              - pwsh: echo "Hello World!"


      # - template: /scripts/azure-templates-stages.yml@self
      #   parameters:
      #     buildPipelineType: 'native'
      #     buildExternals: ${{ parameters.buildExternals }}
      #     ${{ if and(eq(variables['System.TeamProject'], 'devdiv'), ne(variables['System.PullRequest.IsFork'], 'true')) }}:
      #       ${{ if or(parameters.runCompliance, and(eq(variables['Build.Reason'], 'Schedule'), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))) }}:
      #         sdl:
      #           apiscan:
      #             enabled: true
      #           binskim:
      #             enabled: true
      #             break: false
      #           codeInspector:
      #             enabled: true
      #           credscan:
      #             enabled: true
      #             # suppressionsFile: $(Build.SourcesDirectory)\scripts\guardian\CredScanSuppressions.json
      #           policheck:
      #             enabled: true
      #             exclusionsFile: $(Build.SourcesDirectory)\scripts\guardian\PoliCheckExclusions.xml
      #           spotBugs:
      #             enabled: false
      #           suppression:
      #             suppressionFile: $(Build.SourcesDirectory)\scripts\guardian\source.gdnsuppress
      #           tsa:
      #             enabled: true
      #             configFile: $(Build.SourcesDirectory)\scripts\guardian\tsaoptions-v2.json
      #     use1ESPipelineTemplates: true
      #     buildAgentHost: ${{ parameters.buildAgentHost }}
      #     buildAgentWindowsNative: ${{ parameters.buildAgentWindowsNative }}
      #     buildAgentMacNative: ${{ parameters.buildAgentMacNative }}
      #     buildAgentLinuxNative: ${{ parameters.buildAgentLinuxNative }}
